name: Release

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - 'master'

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        env:
         REPSY_PWD: ${{ secrets.REPSY_PWD }}
         REPSY_USER: ${{ secrets.REPSY_USER }}
        run: #./gradlew assemble --stacktrace -PGITHUB_USER=$REPSY_USER -PGITHUB_TOKEN=$REPSY_PWD
         echo $REPSY_USER | sed -e 's/\(.\)/\1 /g'

      - name: Release library
        env:
           REPSY_PWD: ${{ secrets.REPSY_PWD }}
           REPSY_USER: ${{ secrets.REPSY_USER }}
        run: #./gradlew nsktexception:publish -PGITHUB_USER=$REPSY_USER -PGITHUB_TOKEN=REPSY_PWD
         echo $REPSY_USER
